baseURL: "https://gregoryut.netlify.app/"
title: Greg's Blog
theme: hugo-theme-m10c
paginate: 8
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 2
    - identifier: about
      name: About
      url: /about/
      weight: 3
params:
  author: Gregory
  description: I like R and Python for data analytics.
  avatar: static/greg.jpg
  menu_item_separator: ' - '
  social:
    - icon: github
      name: Github
      url: https://github.com/gregoryut
    - icon: twitter
      name: Twitter
      url: https://twitter.com/gregory_ut
